### ISSUE TITLE
Throws fatal error when authenticating

### ISSUE THREAD

**Issue by aarbrown** [nitecon/zfcuser-ldap#2]
Hello,

After installing the module, I'm getting the following fatal error after attempting to authenticate via ZfcUser's login form:

Catchable fatal error: Argument 2 passed to ZfcUserLdap\Mapper\User::__construct() must be an instance of ZfcUserLdap\Options\ModuleOptions, instance of ZfcUser\Options\ModuleOptions given, called in vendor/nitecon/zfcuser-ldap/src/ZfcUserLdap/Authentication/Adapter/Ldap.php on line 51 and defined in vendor/nitecon/zfcuser-ldap/src/ZfcUserLdap/Mapper/User.php on line 28

Any thoughts on this?  Do I need to add configuration options for ZfcUserLdap in my config/autoload (other than ldap settings)?

Thanks

**Comment by nitecon** [comment]
Not an issue please see issue #1 as that contains the instructions, you're seeing the issues as you are trying to use the auth handler directly and its intended to work as a plugin to zfcuser.
