### ISSUE TITLE
zfcUserAuthentication()->getIdentity()->getUsername()

### ISSUE THREAD

**Issue by rodneyo** [nitecon/zfcuser-ldap#7]
I'm not sure if this is a bug or a misconfiguration on my part, but I could you some advice on the following:

I have zfcUser and zfcUserLdap working in terms of authenticating a user against the ldap directory.  Login, Logout, checking to see if the user has an identity works great.  The problem is when I try to use the zfcUserAuthentication()->getIdentity()->getUsername(), getDisplayname() etc it always returns empty. 

During my debugging it properly sets these values in the user->entity, but I can never retrieve the values using the any of the zfcUser helpers.  As far as I can tell the zfcUser methods to retrieve username, email etc should just work if the auth adapter is connecting properly.  Does zfcUser still require the user database even when using ldap as the auth adapter?

Has anyone else had this issue?   Any advice would greatly be appreciated

**Comment by heronour** [comment]
Hello Sire
I have error in this method I have configured all like you tell us in your readme.md file 
ZfcUserLdap\Authentication\Adapter\Ldap->authenticate( )
can you helpe ?
